apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy001
  name: deploy001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy001
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy001
    spec:
      containers:
      - image: dockerimage
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
